package io.github.paulcharp.diveslate.core

import java.io.File
import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Holds this port to the behaviour of the Python implementation.
 *
 * The cases are not written here — they are read from `conformance/specs.json`,
 * generated by `tools/export_oracle.py`. That matters: hand-copied expectations
 * drift, and the ones worth having are exactly the ones nobody would think to
 * write twice. The fixture records refusals as deliberately as conversions,
 * because a port that accepts `'30 fathoms'` as 30 m is wrong in a way no
 * accepted-input case would catch.
 *
 * A failure here means Kotlin and Python disagree. Fix the Kotlin — do not
 * regenerate the fixture to make it pass.
 */
class UnitsConformanceTest {

    private companion object {
        val specs: JsonObject get() = Fixtures.specs

        /** The fixtures round to six places, so compare within that. */
        const val TOLERANCE = 1e-6
    }

    private fun cases(section: String): JsonArray =
        specs[section]?.jsonArray ?: fail("specs.json has no '$section' section")

    private fun assertClose(expected: Double, actual: Double, what: String) {
        assertTrue(
            abs(expected - actual) < TOLERANCE,
            "$what: expected $expected, got $actual",
        )
    }

    /**
     * Run one parser over every case the oracle recorded for it.
     *
     * A case carries either `out` (the value Python produced) or `error` (Python
     * refused it). Both are asserted: silently accepting input Python rejects is
     * the more dangerous of the two failures, because it produces a number.
     */
    private fun checkParser(name: String, parse: (String) -> Double) {
        val units = specs["units"]?.jsonObject ?: fail("specs.json has no 'units'")
        val entries = units[name]?.jsonArray ?: fail("no cases for $name")
        assertTrue(entries.isNotEmpty(), "no cases for $name")

        for (case in entries) {
            val obj = case.jsonObject
            val input = obj.getValue("in").jsonPrimitive.content
            val expected = obj["out"]

            if (expected == null || expected is JsonNull) {
                val error = obj["error"]?.jsonPrimitive?.content
                    ?: fail("$name('$input') has neither out nor error")
                try {
                    val got = parse(input)
                    fail("$name('$input') should raise $error but returned $got")
                } catch (_: UnitException) {
                    // Refused, as the oracle records.
                }
            } else {
                val want = (expected as JsonPrimitive).content.toDouble()
                assertClose(want, parse(input), "$name('$input')")
            }
        }
    }

    @Test
    fun `depth parsing matches the oracle`() = checkParser("parse_depth_m", ::parseDepthMetres)

    @Test
    fun `duration parsing matches the oracle`() =
        checkParser("parse_duration_s", ::parseDurationSeconds)

    @Test
    fun `pressure parsing matches the oracle`() =
        checkParser("parse_pressure_bar", ::parsePressureBar)

    @Test
    fun `temperature parsing matches the oracle`() =
        checkParser("parse_temperature_c", ::parseTemperatureCelsius)

    @Test
    fun `volume parsing matches the oracle`() = checkParser("parse_volume_l", ::parseVolumeLitres)

    @Test
    fun `percent parsing matches the oracle`() = checkParser("parse_percent", ::parsePercent)

    @Test
    fun `minutes always round up`() {
        for (case in cases("ceil_minutes")) {
            val obj = case.jsonObject
            val seconds = obj.getValue("in").jsonPrimitive.content.toDouble()
            val expected = obj.getValue("out").jsonPrimitive.content.toInt()
            assertEquals(expected, ceilMinutes(seconds), "ceilMinutes($seconds)")
        }
    }

    @Test
    fun `metres always round up`() {
        for (case in cases("ceil_metres")) {
            val obj = case.jsonObject
            val metres = obj.getValue("in").jsonPrimitive.content.toDouble()
            val expected = obj.getValue("out").jsonPrimitive.content.toInt()
            assertEquals(expected, ceilMetres(metres), "ceilMetres($metres)")
        }
    }

    @Test
    fun `formatted minutes match the oracle`() {
        for (case in cases("format_minutes")) {
            val obj = case.jsonObject
            val seconds = obj.getValue("in").jsonPrimitive.content.toDouble()
            val expected = obj.getValue("out").jsonArray.map { it.jsonPrimitive.content }
            val (value, unit) = formatMinutes(seconds)
            assertEquals(expected, listOf(value, unit), "formatMinutes($seconds)")
        }
    }

    @Test
    fun `formatted durations match the oracle`() {
        for (case in cases("format_duration")) {
            val obj = case.jsonObject
            val seconds = obj.getValue("in").jsonPrimitive.content.toDouble()
            val expected = obj.getValue("out").jsonPrimitive.content
            assertEquals(expected, formatDuration(seconds), "formatDuration($seconds)")
        }
    }
}
