import java.util.Properties

// AGP 9 carries Kotlin support itself and refuses the standalone
// org.jetbrains.kotlin.android plugin alongside it.
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.plugin.compose")
}

/**
 * Release signing, from the environment first and local.properties second.
 *
 * The environment is what CI uses: the workflow decodes the keystore from a
 * repository secret and exports these four names, so nothing has to write a
 * properties file inside a checkout that might get archived. Locally, the same
 * four go in local.properties, which is gitignored.
 *
 *   DIVESLATE_STORE_FILE / storeFile          absolute path to the .jks
 *   DIVESLATE_STORE_PASSWORD / storePassword
 *   DIVESLATE_KEY_ALIAS / keyAlias
 *   DIVESLATE_KEY_PASSWORD / keyPassword
 *
 * See docs/RELEASING.md for generating the keystore. It is generated by you and
 * never enters the repo: losing it means never being able to update an already
 * installed app, because Android identifies an app by its signature.
 *
 * With none of them set, the release build falls back to the debug key so
 * `assembleRelease` still yields something installable. That is fine for
 * sideloading onto your own phone and useless for distribution — every SDK
 * install shares that key, so an app signed with it cannot be updated by one
 * signed with a real key later. The fallback therefore says so out loud, and
 * the release workflow reads the certificate back off the finished APK rather
 * than trusting this to have worked.
 *
 * A partial set is refused rather than half-applied, the same way the derived
 * figures degrade to nothing instead of to a guess: three of the four names
 * would otherwise fall through to the debug key and look like success.
 */
val localProperties: Properties? =
    rootProject.file("local.properties")
        .takeIf { it.exists() }
        ?.let { file -> Properties().apply { file.inputStream().use { load(it) } } }

val releaseSigning: Map<String, String>? =
    run {
        val names =
            mapOf(
                "storeFile" to "DIVESLATE_STORE_FILE",
                "storePassword" to "DIVESLATE_STORE_PASSWORD",
                "keyAlias" to "DIVESLATE_KEY_ALIAS",
                "keyPassword" to "DIVESLATE_KEY_PASSWORD",
            )
        val fromEnv = names.mapValues { (_, env) -> System.getenv(env) }
        val source = if (fromEnv.values.any { !it.isNullOrBlank() }) fromEnv else
            names.mapValues { (property, _) -> localProperties?.getProperty(property) }

        val present = source.filterValues { !it.isNullOrBlank() }.mapValues { it.value!! }
        when (present.size) {
            0 -> null
            names.size -> present
            else ->
                throw GradleException(
                    "Release signing is half-configured — missing " +
                        names.keys.minus(present.keys).joinToString(", ") +
                        ". Set all four or none; see docs/RELEASING.md.",
                )
        }
    }

android {
    namespace = "io.github.paulcharp.diveslate"
    // 37 is what the AndroidX libraries in use demand; targetSdk stays at the
    // behaviour level actually tested against.
    compileSdk = 37

    defaultConfig {
        applicationId = "io.github.paulcharp.diveslate"
        // 29 for scoped storage: saving to the gallery via MediaStore needs
        // RELATIVE_PATH and IS_PENDING, and the alternative below that is a
        // runtime permission plus deprecated file APIs. Android 10 is a fair
        // floor for a phone that also runs Subsurface-mobile and Instagram.
        minSdk = 29
        targetSdk = 36
        versionCode = 10
        versionName = "0.2.3"
    }

    signingConfigs {
        if (releaseSigning != null) {
            create("release") {
                storeFile = file(releaseSigning.getValue("storeFile"))
                storePassword = releaseSigning.getValue("storePassword")
                keyAlias = releaseSigning.getValue("keyAlias")
                keyPassword = releaseSigning.getValue("keyPassword")
                // Both modern schemes. v1 is JAR signing, irrelevant above
                // API 24 and minSdk here is 29; v2 and v3 are what the platform
                // verifies, and v3 is what would allow the key to be rotated
                // without the app losing its identity.
                enableV1Signing = false
                enableV2Signing = true
                enableV3Signing = true
            }
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.findByName("release")
                ?: signingConfigs.getByName("debug").also {
                    logger.warn(
                        "Dive Slate: no release keystore configured — signing with the " +
                            "shared debug key. Installable, but not distributable, and " +
                            "an install of this build cannot be updated by a properly " +
                            "signed one. See docs/RELEASING.md.",
                    )
                }

            // R8 on. The app is small and reflection-free — kotlinx-serialization
            // is test-only and never reaches the APK — so there is nothing here
            // for shrinking to break. Verified by installing the shrunk build and
            // exercising it, not by assuming.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    buildFeatures {
        compose = true
        // For BuildConfig.VERSION_NAME on the start screen. Knowing which build
        // is on a phone is the first question every bug report needs answered.
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation(project(":core"))

    implementation(platform("androidx.compose:compose-bom:2026.08.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-core")
    implementation("androidx.activity:activity-compose:1.13.0")
    implementation("androidx.core:core-ktx:1.19.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.11.0")

    debugImplementation("androidx.compose.ui:ui-tooling")
    implementation("androidx.compose.ui:ui-tooling-preview")
}
