import java.util.Properties

// AGP 9 carries Kotlin support itself and refuses the standalone
// org.jetbrains.kotlin.android plugin alongside it.
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.plugin.compose")
}

/**
 * Release signing: the same four values, from the environment or a properties
 * file, whichever turns up first.
 *
 *   DIVESLATE_STORE_FILE / storeFile          path to the keystore
 *   DIVESLATE_STORE_PASSWORD / storePassword
 *   DIVESLATE_KEY_ALIAS / keyAlias
 *   DIVESLATE_KEY_PASSWORD / keyPassword
 *
 * The environment comes first because that is what CI uses: the workflow decodes
 * the keystore from a repository secret and exports these names, so nothing has
 * to write a credentials file inside a checkout that might get archived.
 *
 * Then keystore.properties, which is the file to use locally, looked for beside
 * this build and at the repository root. local.properties still works and is
 * checked last, but it is the worse home for a password: it is also where the
 * SDK path lives, which means Android Studio owns that file and rewrites it.
 * Everything but the SDK path is safer somewhere Studio has no opinion about.
 *
 * All of them are gitignored. See docs/RELEASING.md for generating the keystore —
 * it is generated by you and never enters the repo, and losing it means never
 * being able to update an already installed app, because Android identifies an
 * app by its signature.
 *
 * With none of them set, the release build falls back to the debug key so
 * `assembleRelease` still yields something installable. That is fine for
 * sideloading onto your own phone and useless for distribution — every SDK
 * install shares that key, so an app signed with it cannot be updated by one
 * signed with a real key later. The fallback therefore says so out loud, and the
 * release workflow reads the certificate back off the finished APK rather than
 * trusting any of this to have worked.
 *
 * A partial set is refused rather than half-applied, the same way the derived
 * figures degrade to nothing instead of to a guess: three of the four names
 * would otherwise fall through to the debug key and look like success.
 */
val signingProperties: Pair<File, Properties>? =
    listOf(
        rootProject.file("keystore.properties"),
        rootProject.file("../keystore.properties"),
        rootProject.file("local.properties"),
    ).firstNotNullOfOrNull { file ->
        file.takeIf { it.isFile }
            ?.let { Properties().apply { it.inputStream().use { stream -> load(stream) } } }
            // A file is only a signing source if it actually names a keystore.
            // local.properties usually holds nothing but sdk.dir.
            ?.takeIf { it.getProperty("storeFile") != null }
            ?.let { file to it }
    }

val releaseSigning: Map<String, String>? =
    run {
        val names =
            mapOf(
                "storeFile" to "DIVESLATE_STORE_FILE",
                "storePassword" to "DIVESLATE_STORE_PASSWORD",
                "keyAlias" to "DIVESLATE_KEY_ALIAS",
                "keyPassword" to "DIVESLATE_KEY_PASSWORD",
            )
        val fromEnv = names.mapValues { (_, env) -> System.getenv(env) }
        val source = if (fromEnv.values.any { !it.isNullOrBlank() }) {
            fromEnv
        } else {
            names.mapValues { (property, _) -> signingProperties?.second?.getProperty(property) }
        }

        val present = source.filterValues { !it.isNullOrBlank() }.mapValues { it.value!! }
        when (present.size) {
            0 -> null
            names.size -> present
            else ->
                throw GradleException(
                    "Release signing is half-configured — missing " +
                        names.keys.minus(present.keys).joinToString(", ") +
                        ". Set all four or none; see docs/RELEASING.md.",
                )
        }
    }

android {
    namespace = "io.github.paulcharp.diveslate"
    // 37 is what the AndroidX libraries in use demand; targetSdk stays at the
    // behaviour level actually tested against.
    compileSdk = 37

    defaultConfig {
        applicationId = "io.github.paulcharp.diveslate"
        // 29 for scoped storage: saving to the gallery via MediaStore needs
        // RELATIVE_PATH and IS_PENDING, and the alternative below that is a
        // runtime permission plus deprecated file APIs. Android 10 is a fair
        // floor for a phone that also runs Subsurface-mobile and Instagram.
        minSdk = 29
        targetSdk = 36
        // versionCode is what the updater compares, and the release workflow
        // refuses a tag whose name disagrees with versionName. Both move
        // together; see docs/RELEASING.md.
        versionCode = 18
        versionName = "0.6.0"
    }

    signingConfigs {
        if (releaseSigning != null) {
            create("release") {
                // A relative storeFile resolves against the file that named it,
                // which is the only base a reader would expect. Gradle's own
                // file() would resolve it against this module instead, two
                // directories away from the properties file being edited.
                val declared = releaseSigning.getValue("storeFile")
                val base = signingProperties?.first?.parentFile ?: rootProject.projectDir
                val keystore = File(declared).takeIf { it.isAbsolute } ?: File(base, declared)
                if (!keystore.isFile) {
                    throw GradleException(
                        "Release keystore not found at ${keystore.absolutePath} " +
                            "(storeFile=$declared). See docs/RELEASING.md.",
                    )
                }
                logger.lifecycle(
                    "Dive Slate: signing release with the key at ${keystore.absolutePath}, " +
                        "configured by ${signingProperties?.first?.name ?: "the environment"}.",
                )

                storeFile = keystore
                storePassword = releaseSigning.getValue("storePassword")
                keyAlias = releaseSigning.getValue("keyAlias")
                keyPassword = releaseSigning.getValue("keyPassword")
                // v1 is JAR signing, dead weight above API 24 and minSdk is 29.
                //
                // Both v2 and v3 are asked for, but the APK this actually
                // produces is v3-only: v3 is verified from API 28, so at minSdk
                // 29 the signer drops the redundant v2 block. Verified by
                // reading the certificate off the APK — a release check
                // asserting "v2 is true" fails every good build here, which is
                // exactly the mistake the workflow made once. v2 stays
                // requested so it reappears by itself if minSdk ever drops
                // below 28. v3 is also what allows the key to be rotated later
                // without the app losing its identity.
                enableV1Signing = false
                enableV2Signing = true
                enableV3Signing = true
            }
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.findByName("release")
                ?: signingConfigs.getByName("debug").also {
                    logger.warn(
                        "Dive Slate: no release keystore configured — signing with the " +
                            "shared debug key. Installable, but not distributable, and " +
                            "an install of this build cannot be updated by a properly " +
                            "signed one. See docs/RELEASING.md.",
                    )
                }

            // R8 on. The app is small and reflection-free — kotlinx-serialization
            // is test-only and never reaches the APK — so there is nothing here
            // for shrinking to break. Verified by installing the shrunk build and
            // exercising it, not by assuming.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    buildFeatures {
        compose = true
        // For BuildConfig.VERSION_NAME on the start screen. Knowing which build
        // is on a phone is the first question every bug report needs answered.
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation(project(":core"))

    implementation(platform("androidx.compose:compose-bom:2026.08.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-core")
    implementation("androidx.activity:activity-compose:1.13.0")
    implementation("androidx.core:core-ktx:1.19.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.11.0")
    // The session state lives in a ViewModel so that a rotation cannot take the
    // open dive log with it, and so an export in progress is not cancelled
    // halfway by one. Pinned to the version lifecycle-runtime already resolves.
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.11.0")
    // The update check runs on lifecycleScope + Dispatchers.IO. Already present
    // transitively via lifecycle and Compose, and pinned to the version they
    // already resolve to — declared only because the code names it directly, and
    // a dependency you use through someone else's is one that can vanish under
    // you in an unrelated upgrade.
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")

    debugImplementation("androidx.compose.ui:ui-tooling")
    implementation("androidx.compose.ui:ui-tooling-preview")

    // Plain JVM unit tests, no device and no Robolectric. What they cover is
    // the logic in this module that never needed Android to begin with — the
    // settings that are persisted, the export filenames, and the validation the
    // updater applies to a release manifest before an APK is installed. Code
    // that genuinely needs the framework (MediaStore, the Canvas painter) is
    // left to be exercised on a phone; a mocked Canvas would only prove the
    // mock agrees with itself.
    testImplementation("junit:junit:4.13.2")
    // org.json is part of Android and is a throwing stub in a unit test. The
    // real implementation on the test classpath is what lets the manifest
    // parser be tested at all; it changes nothing about the APK, which uses the
    // framework's copy.
    testImplementation("org.json:json:20240303")
}
